# This is a basic workflow to help you get started with Actions

name: CI_qcef

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "qcef" ]
  pull_request:
    branches: [ "qcef" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE so your job can access it
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: 'martyr-deepin/qcef'
          path: 'qcef'
          ref: '1.1.8'
          submodules: 'recursive'

          #debug
      - name: fix
        run: |
          pwd
          cp qcef_dialog_handler.cpp qcef/src/core/
        
          #Runs a set of commands using the runners shell
      - name: Install build dependence
        uses: ConorMacBride/install-package@v1.1.0
        with:
          apt: debhelper ca-certificates cmake git libasound2 libfl-dev libfontconfig1-dev libgconf-2-4 libgtk2.0-dev libglib2.0-dev libharfbuzz-dev libnspr4 libnss3 libpulse0 libqt5webchannel5-dev libqt5x11extras5-dev libx11-dev libxext-dev libxss-dev libxtst-dev mesa-common-dev pkg-config qtbase5-private-dev qttools5-dev-tools
              #      - name: Install go dependence
              #        run: |
              #          go get github.com/smartystreets/goconvey
              #          go get github.com/howeyc/fsnotify
              #          go get gopkg.in/check.v1
              #          go get github.com/linuxdeepin/go-x11-client

      - name: Build debian package
        run: | 
          cd qcef
          dpkg-buildpackage

      - name: Collect outputs
        run: |
          ls ~/
          mkdir ~/out
          cp ~/*.deb ~/*.tar.xz  ~/out/

      - name: Release
        uses: fnkr/github-action-ghr@v1.3
        with:
          GHR_PATH: '~/out/'
