# This is a basic workflow to help you get started with Actions

name: CI_qcef

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "qcef" ]
  pull_request:
    branches: [ "qcef" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ['amd64','386','arm64','arm']

    container:
      image: ubuntu:bionic
      options: --platform ${{ matrix.arch }}

    steps:
      - name: Install build dependence
        uses: ConorMacBride/install-package@v1.1.0
        with:
          apt: debhelper ca-certificates cmake git libasound2 libfl-dev libfontconfig1-dev libgconf-2-4 libgtk2.0-dev libglib2.0-dev libharfbuzz-dev libnspr4 libnss3 libpulse0 libqt5webchannel5-dev libqt5x11extras5-dev libx11-dev libxext-dev libxss-dev libxtst-dev mesa-common-dev pkg-config qtbase5-private-dev qttools5-dev-tools

      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: 'martyr-deepin/qcef'
          path: 'qcef'
          ref: '1.1.8'
          submodules: 'recursive'
      - run: |
          git submodule update --init --recursive
          git submodule update --remote

          #debug
      - name: fix
        run: |
          pwd
          cp qcef_dialog_handler.cpp qcef/src/core/
        
          #Runs a set of commands using the runners shell
              #      - name: Install go dependence
              #        run: |
              #          go get github.com/smartystreets/goconvey
              #          go get github.com/howeyc/fsnotify
              #          go get gopkg.in/check.v1
              #          go get github.com/linuxdeepin/go-x11-client

      - name: Build debian package
        run: | 
          cd qcef
          dpkg-buildpackage

      - name: Collect outputs
        run: |
          mkdir ./out
          cp $(find ~/ -name "*.deb") ./out/
          cp $(find ~/ -name "*.tar.xz")  ./out/

      - name: Release
        uses: fnkr/github-action-ghr@v1.3
        with:
          GHR_PATH: out/
