# This is a basic workflow to help you get started with Actions

name: CI_qcef

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "qcef" ]
  pull_request:
    branches: [ "qcef" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: 'martyr-deepin/qcef'
          path: 'qcef'
          ref: '1.1.8'
          submodules: 'recursive'

          #debug
      - name: fix
        run:
          pwd
          cp qcef_dialog_handler.cpp qcef/src/core/
       Runs a set of commands using the runners shell
        
      - name: Install build dependence
        run: |
          apt update
          apt install \
              debhelper cmake libfl-dev libgtk2.0-dev libharfbuzz-dev \
              libpulse0 libqt5webchannel5-dev libqt5x11extras5-dev libxss-dev libxtst-dev \
              mesa-common-dev qtbase5-private-dev qttools5-dev-tools

              #      - name: Install go dependence
              #        run: |
              #          go get github.com/smartystreets/goconvey
              #          go get github.com/howeyc/fsnotify
              #          go get gopkg.in/check.v1
              #          go get github.com/linuxdeepin/go-x11-client

      - name: Build debian package
        run: | 
          dpkg-buildpackage
